# Generated by Django 5.1.4 on 2025-03-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_cart_food_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='food',
            new_name='food_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='table_number',
            new_name='table_id',
        ),
    ]
