# Generated by Django 5.1.4 on 2025-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_food_id_cart_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='cart',
            field=models.ManyToManyField(related_name='checkouts', to='api.cart'),
        ),
    ]
