# Generated by Django 5.1.4 on 2025-03-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_checkout_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
