# Generated by Django 5.1.4 on 2025-03-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_cart_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_category_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
