# Generated by Django 5.1.4 on 2025-03-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_food_food_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_category_obj',
        ),
    ]
