# Generated by Django 5.1.4 on 2025-03-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_food_food_category_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_category',
        ),
        migrations.AddField(
            model_name='seller',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prep_time', models.IntegerField(null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], max_length=50, null=True)),
                ('food_items', models.ManyToManyField(to='api.cart')),
                ('table_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
    ]
