# Generated by Django 5.1.4 on 2025-03-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_seller_seller_category_seller_otp_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='seller_category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hospital Canteen', 'Hospital Canteen'), ('College Canteen', 'College Canteen')], default='Hotel', max_length=200),
        ),
    ]
