# Generated by Django 5.1.4 on 2025-03-17 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_seller_seller_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='seller_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
