# Generated by Django 5.1.4 on 2025-03-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_table_seller_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seller_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sellercategory'),
        ),
    ]
