# Generated by Django 5.1.4 on 2025-03-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_table_seller_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='seller_category',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Hospital Canteen', 'Hospital Canteen'), ('College Canteen', 'College Canteen')], default='Hotel', max_length=200),
        ),
    ]
