# Generated by Django 5.1.4 on 2025-03-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_checkout_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='description',
            new_name='descriptions',
        ),
    ]
