# Generated by Django 5.1.4 on 2025-03-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='descriptions',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
